name: CI
on:
  push:
    branches: [master]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x
      - name: Test and bundle
        run: |
          deno test
          deno bundle stars.ts > stars.js
          ls .
      - name: Install SSH client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy Github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: .

